# Generated by Django 4.1.7 on 2025-12-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0001_initial'),
    ]

    operations = [
    ]
